spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/mass?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 225588
          driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5      # 连接池初始化大小
      min-idle: 5          # 最小空闲连接数
      max-active: 20       # 最大活跃连接数

mass:
  redis:
    single:
      enabled: true  # 这个必须设置为 true
      address: "redis://127.0.0.1:6379"
      database: 6
      connect-timeout: 3000
      timeout: 3000
      retry-attempts: 3
      retry-interval: 1500


management:
  endpoints:
    web:
      exposure:
        include: "conditions"
