spring:
  application:
    name: mass-module-erp
  redis:
    host: 127.0.0.1
    port: 6379
    database: 6
    timeout: 3s

mass:
  redis:
    learning:
      product-cache-ttl: 30m
      null-cache-ttl: 2m
      lock-wait-time: 3s
      lock-lease-time: 15s
      hot-key-loops: 1000
      big-key-item-count: 5000
      avalanche-key-count: 20
      avalanche-base-ttl: 10m
      bloom-filter-expected-insertions: 5000
      bloom-filter-false-probability: 0.01